soccer/controllers/CountryController.php
<?php

namespace soccer\controllers;

use core\readModels\CountryReadRepository;
use core\readModels\Soccer\TournamentReadRepository;
use yii\web\Controller;

class CountryController extends Controller
{
    public $layout = 'family_key';

    public $countries;
    public $tournaments;

    public function __construct($id, $module, CountryReadRepository $countries, TournamentReadRepository $tournaments, $config = [])
    {
        parent::__construct($id, $module, $config);
        $this->countries = $countries;
        $this->tournaments = $tournaments;
    }

    public function actionIndex($id)
    {
        $tournaments = $this->tournaments->getTournamentsByCountryId($id);

        return $this->render('index', ['tournaments' => $tournaments]);
    }

}

soccer/controllers/DataController.php
<?php

namespace soccer\controllers;

use core\entities\Rockncontroll\Items;
use core\entities\Rockncontroll\RadioItem;
use Yii;
use yii\base\ErrorException;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\helpers\Url;

class DataController extends Controller
{
    function getCurrentTrackText()
    {
        //$file = html_entity_decode(strip_tags(file("http://88.212.253.193:8000/status.xsl?mount=/test")[68]));
        //if(isset(file(\Yii::getAlias('@radio_test_tags'))[68]))
        //    $file = html_entity_decode(strip_tags(file(\Yii::getAlias('@radio_test_tags'))[68]));
        //var_dump(file('http://88.85.67.159:8000/test.xspf'));
        //var_dump($this->parseXmlTitle('http://88.85.67.159:8000/test.xspf'));

        $title = $this->parseXmlTitle(\Yii::getAlias('@radio_test_tags'));
        //exit;
        //else $file = "";
        $item = RadioItem::find()->where(['like', 'audio', trim($title)])->one();
        //var_dump($item);
        if($item) return $item->title . '<br>';
        //echo html_entity_decode(strip_tags(file("http://88.212.253.193:8000/status.xsl?mount=/test")[68])). '<br>';
        return $title;

    }

    public function actionInvertRandImg()
    {
        $item = Items::find()
            ->where('cat_id = 259')
            ->orderBy(['rand()' => SORT_DESC])
            ->limit(1)
            ->one();
        //\core\helpers\Helper::invertImageColor($item->img);
        return '<img class="pic css-adaptive" src="' . Url::to('@static/'.$item->img) . '?cash='.time().'"/>';
    }

}

soccer/controllers/TournamentController.php
<?php

namespace soccer\controllers;

use core\readModels\Soccer\MatchReadRepository;
use core\readModels\Soccer\TournamentReadRepository;
use yii\web\Controller;

class TournamentController extends Controller
{
    public $layout = 'family_key';

    public $matches;
    public $tournaments;

    const ALL_MATCHES = 0;
    const VICTORY_MATCHES = 1;
    const TIE_MATCHES = 2;
    const DEFEAT_MATCHES = 3;

    public function __construct($id, $module, MatchReadRepository $matches, TournamentReadRepository $tournaments, $config = [])
    {
        parent::__construct($id, $module, $config);
        $this->matches = $matches;
        $this->tournaments = $tournaments;
    }

    public function actionIndex($id)
    {
        $matches = $this->matches->getMatchesByTournamentId($id);
        //var_dump($tournament_name); exit;
        return $this->render('index', [
            'matches' => $matches,
        ]);
    }

    public function actionAll($id)
    {
        $country_names = $this->tournaments->getAllTournamentsNamesByCountryId($id);
        return  json_encode($country_names);
    }

    public function actionTeams($id)
    {
        $teams_names = $this->matches->getAllTournamentTeams($id);
        return  json_encode($teams_names);
    }

    public function actionAllTeams()
    {
        $teams_names = $this->matches->getAllTeams();
        return  json_encode($teams_names);
    }


    public function actionGetMatchesOfTwoTeams($team1, $team2)
    {
        $matches = $this->matches->getMatchesOfTwoTeams($team1, $team2);
        $tournament_matches = $this->matches->allMatchesOfTwoTeams($team1, $team2);
        $team_names = [$team1, $team2];

        return $this->renderPartial('index', [
            'matches' => $matches,
            'tournament_name' => 'Матчи команд '.$team1.' и '.$team2,
            'tournament_id' => 0,
            'team_name' => null,
            'summary' => $this->matches->getSortedTeamsSummary($team_names, $tournament_matches)
        ]);
    }

    public function actionGetTeamsOfTournament($name)
    {
        $tournament_id = $this->tournaments->getIdByTournamentName($name);

        return $this->renderPartial('teams', [
            'tournament_id' => $tournament_id,
        ]);
    }

    public function actionGetMatchesOfTeam($name, $tournament_id, $filter=self::ALL_MATCHES)
    {
        if ((int)$filter == self::VICTORY_MATCHES)
            $matches = $this->matches->getMatchesOnlyTeamVictory($name, (int)$tournament_id);
        elseif ((int)$filter == self::TIE_MATCHES)
            $matches = $this->matches->getMatchesOnlyTeamTie($name, (int)$tournament_id);
        elseif ((int)$filter == self::DEFEAT_MATCHES)
            $matches = $this->matches->getMatchesOnlyTeamDefeat($name, (int)$tournament_id);
        else
            $matches = $this->matches->getMatchesByTeamName($name, $tournament_id);

        $tournament_matches = $this->matches->allTournamentMatches($tournament_id);
        $tournament_name = $this->tournaments->getNameById($tournament_id);
        $team_names = $this->matches->getAllTournamentTeams($tournament_id);

        return $this->renderPartial('index', [
            'matches' => $matches,
            'tournament_name' => $tournament_name,
            'tournament_id' => $tournament_id,
            'team_name' => $name,
            'summary' => $this->matches->getSortedTeamsSummary($team_names, $tournament_matches)
        ]);
    }

    public function actionGetMatchesOfTour($tour, $tournament_id)
    {
        $matches = $this->matches->getMatchesByTour($tour, (int)$tournament_id);
        $tournament_matches = $this->matches->allTournamentMatchesToTour($tour, (int)$tournament_id);
        $tournament_name = $this->tournaments->getNameById($tournament_id);
        $team_names = $this->matches->getAllTournamentTeams($tournament_id);

        return $this->renderPartial('index', [
            'matches' => $matches,
            'tournament_name' => $tournament_name,
            'tournament_id' => $tournament_id,
            'team_name' => null,
            'summary' => $this->matches->getSortedTeamsSummary($team_names, $tournament_matches)
        ]);
    }

}

soccer/views/tournament/_matches.php
<?php
/* @var \core\entities\Soccer\Match[] $matches*/
/* @var string $tour*/
?>

    <style>

        .table > tbody > tr > td{
            color: rgb(255, 215, 0);
            font-size: 15px;
            cursor: pointer;
            padding-left: 3px;
        }
        .table > tbody > tr.firsts td{
            color: rgb(255, 140, 37);
        }
        .table > tbody > tr.lasts td{
            color: rgb(129, 236, 255);
        }
        h3{color: rgb(255, 215, 0); text-align: center}

        .collor_match {color: #b67b69}
        .fix_width {width: 10%}
        span{
            font-size: 13px;
        }

        .view {
            width: 97%;
            max-width:900px;
            margin: 1em auto;
            font-size: 18px;
            padding: 1em;
            /*border-radius: 10px;*/
            /*background: rgb(16, 56, 10) radial-gradient(circle at 0 0, rgba(8, 21, 11, 0.65), rgba(6, 47, 7, 0.35));*/
            box-shadow:
                inset rgba(250,250,250,.9) -8px 8px 8px,
                inset rgba(255,255,255,.9) 8px 3px 8px,
                rgba(0,0,0,.8) 3px 3px 8px -3px;
            background:
                repeating-linear-gradient(
                    transparent,transparent 21px, rgb(100,100,100) 22px
                ),
                repeating-linear-gradient(
                    90deg,
                    transparent,transparent 21px, rgb(100,100,100) 22px
                );

        }
        #match_date {
            color:#009900;
            font-size: 15px;
            float: right;
            padding-top: 3px;
            margin: 0;
            padding-right: 10px;
        }

        #match_tour{
            color:#009900;
            font-size: 18px;
            margin: 0;
            padding-left: 10px;

        }

        #match_tour:hover{
            cursor: pointer;
            color: #879971;
        }

        #mems_match {
            color:#e0bd69;
            font-size: 18px;

            margin: 0;
            /*width: 700px;*/
            table-layout: fixed;
        }

        #bet {
            width: 750px;
            margin-left: 70px;
        }

        .left_bet_cyph{

            text-align: right;
            width: 250px;
            color: #0088e4;
            font-size: 30px;
        }

        .center_bet_cyph{
            text-align: center;
            width: 250px;
            color: #0088e4;
            font-size: 30px;

        }

        .right_bet_cyph{
            text-align: left;
            width: 250px;
            color: #0088e4;
            font-size: 30px;

        }

        .left_bet{

            text-align: right;
            width: 250px;
            color: #0088e4;

        }

        .center_bet{
            text-align: center;
            width: 250px;
            color: #0088e4;


        }

        .right_bet{
            text-align: left;
            width: 250px;
            color: #0088e4;

        }


        #ud{
            color: #7db0e0;
            font-size: 15px;

            margin: 0;
            /*width: 700px;*/
            table-layout: fixed;
        }

        #vlad{
            color: #e08129;
            font-size: 15px;

            margin: 0;
            /*width: 700px;*/
            table-layout: fixed;
        }

        #coach{
            color: #24e08d;
            font-size: 15px;

            margin: 0;
            /*width: 700px;*/
            table-layout: fixed;
        }

        #keeper{
            color: #a2e0d1;
            font-size: 15px;

            margin: 0;
            /*width: 700px;*/
            table-layout: fixed;
        }

        #falls{
            color: #e05d1d;
            font-size: 15px;

            margin: 0;
            /*width: 700px;*/
            table-layout: fixed;
        }


        #stavki{
            color: #e0c400;
            font-size: 15px;

            margin: 0;
            /*width: 700px;*/
            table-layout: fixed;
        }

        .left{

            text-align: right;
            width: 40%;
            padding-left: 20px;
            /*word-wrap: break-word;*/
        }

        .small-font{
            font-size: 13px;
            color: rgb(255, 235, 59);
        }

        .center{
            text-align: center;
            width: 50px;
            padding: 5px;

        }

        .right{
            text-align: left;
            width: 40%;
            padding-right: 20px;
            /*word-wrap: break-word;*/
        }

        #teams_data{
            width: 100%;
        }

        .info{
            font-size: 12px;
            color: #cf4b25;
            text-align: center;
        }

        #mems_goal {
            color:#BCE774;
            font-size: 14px;

            margin: 0;
            /*width: 700px;*/
            table-layout: fixed;
        }

        #mems_goal p{
            text-align: center;
        }

        #substit{
            color: #9E771D;
            font-size: 15px;

            margin: 0;
            /*width: 700px;*/
            table-layout: fixed;
        }


        @media(min-width:100px) and (max-width: 550px) {
            #planet {
                display: none;
            }

            .news {
                font-size: 10px;
            }

            #blinkingText1 {

                font-size: 12px;
            }

            h3 {
                font-size: 17px;
            }

            h2 {
                font-size: 20px;
            }

            .head_champ {
                font-size: 15px;
            }
            .timer {
                font-size: 15px;
            }
            .emb {
                width: 18%;
            }
            /*.left, .right, .center{
                font-size: 13px;
            }
            #mems_match .left,  #mems_match .right {

                font-size: 17px;

            }
            */


        }

    </style>
    <h3><?=$tour?></h3>
<?= \yii\widgets\ListView::widget( [
    'dataProvider' => $matches,
    'itemOptions' => ['class' => 'item'],
    'itemView' => function ($model, $key, $index, $widget) {
        return $this->render('match', ['match' => $model]);
    },
    'pager' => ['class' => \kop\y2sp\ScrollPager::class]
]);

soccer/views/tournament/_summary.php
<?php
/* @var \core\entities\Soccer\TeamSummary[] $summary */
/* @var integer $tournament_id */
/* @var string $team_name */
?>
<style>
    .table_blur {
        background: #363b3f;
        border-collapse: collapse;
        text-align: left;
        font-size: 20px;
    }
    .table_blur th {
        border-top: 1px solid #777777;
        border-bottom: 1px solid #777777;
        box-shadow: inset 0 1px 0 #999999, inset 0 -1px 0 #999999;
        background: linear-gradient(#9595b6, #5a567f);
        color: white;
        padding: 10px 15px;
        position: relative;
    }
    .table_blur th:after {
        content: "";
        display: block;
        position: absolute;
        left: 0;
        top: 25%;
        height: 25%;
        width: 100%;
        background: linear-gradient(rgba(255, 255, 255, 0), rgba(255,255,255,.08));
    }
    .table_blur tr:nth-child(odd) {
        background: #768089;
        background-color: rgb(47, 46, 42);
        background-image: linear-gradient(to bottom, rgb(20, 19, 19), rgb(255, 215, 0));
        background-repeat: repeat-x;
    }
    .table_blur th:first-child {
        border-left: 1px solid #777777;
        border-bottom:  1px solid #777777;
        box-shadow: inset 1px 1px 0 #999999, inset 0 -1px 0 #999999;
    }
    .table_blur th:last-child {
        border-right: 1px solid #777777;
        border-bottom:  1px solid #777777;
        box-shadow: inset -1px 1px 0 #999999, inset 0 -1px 0 #999999;
    }
    .table_blur td {
        border: 1px solid #e3eef7;
        padding: 10px 15px;
        position: relative;
        transition: all 0.5s ease;
    }
    .centr{
        text-align: center;
    }
    .red{
        color: rgb(255, 235, 59);
    }
    /*
    .table_blur tbody:hover td {
        color: transparent;
        text-shadow: 0 0 3px #a09f9d;
    }
    .table_blur tbody:hover tr:hover td {
        color: #444444;
        text-shadow: none;
    }
    */
    @media (max-width: 768px) {
        .table_blur {
            font-size: 15px;
        }
        .table_blur td {
            padding: 3px 2px;
        }
        .firsts td{
            cursor: pointer;
        }
    }
</style>
<table class="table_blur">
    <tbody>
    <tr>
        <td>м</td>
        <td class="fix_width">к</td>
        <td class="centr">и</td>
        <td class="centr">в</td>
        <td class="centr">н</td>
        <td class="centr">п</td>
        <td class="centr">рм</td>
        <td class="centr">о</td>
    </tr>
    <?php $i=1; foreach ($summary as $sum) :
        //echo $team_name.'<br>'.$sum->row_team; exit;
        ?>
        <?php if($sum->row_team == $team_name) : ?>
        <tr class="firsts red" id="t_<?=$i?>">
        <?php else : ?>
        <tr class="firsts" id="t_<?=$i?>">
        <?php endif; ?>
        <td><?=$i?></td>
        <td width="30%" style="cursor: pointer;"
            onclick="getTournamentMatchesOfTeam('<?=$sum->row_team ?>',
                    '<?=$tournament_id?>', 't_<?=$i++?>');"><?= $sum->team ?>
        </td>
        <td class="centr"><?= $sum->games ?></td>
        <td class="centr" style="cursor: pointer;" title="Показать победы"
            onclick="getTournamentMatchesOfTeam('<?=$sum->row_team ?>',
                '<?=$tournament_id?>', 't_<?=$i?>', 1);"><?= $sum->victories ?> </td>
        <td class="centr" style="cursor: pointer;" title="Показать ничьи"
            onclick="getTournamentMatchesOfTeam('<?=$sum->row_team ?>',
                    '<?=$tournament_id?>', 't_<?=$i?>', 2);"><?= $sum->ties ?></td>
        <td class="centr" style="cursor: pointer;" title="Паказать поражения"
            onclick="getTournamentMatchesOfTeam('<?=$sum->row_team ?>',
                    '<?=$tournament_id?>', 't_<?=$i?>', 3);"><?= $sum->defeats ?></td>
        <td width="20%" class="centr"><?= $sum->gets ?> : <?= $sum->lets ?></td>
        <td class="centr"><?= $sum->balls ?></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>

soccer/views/tournament/match.php
<?php
/* @var \core\entities\Soccer\Match $match*/
/* @var  string $team_name */
?>
<style>
    table{
        width: 100%;
    }
    .view{
        display: none;
    }
    .mtch{
        font-size: 20px;
        text-align: center;
    }
</style>

<hr>

  <?php if(strstr($match->host, $team_name) && $match->gett > $match->lett) : ?>
    <p class="mtch" id="head_<?= $match->id ?>"
        onclick="$('#view_<?= $match->id ?>').show(); $(this).hide();"
        style="color: rgb(148, 245, 12)">
        <?=\core\helpers\SoccerHelper::getTourFromMatchTournament($match->tournament)?> : <?=$match->date ?> <br>
        <?=$match->host ?> - <?=$match->guest ?> - <?= $match->gett; ?>:<?= $match->lett; ?>
    </p>
    <?php elseif(strstr($match->guest, mb_strcut($team_name,2)) && $match->gett < $match->lett) : ?>
        <p class="mtch" id="head_<?= $match->id ?>"
           onclick="$('#view_<?= $match->id ?>').show(); $(this).hide();"
           style="color: rgb(148, 245, 12)">
        <?=\core\helpers\SoccerHelper::getTourFromMatchTournament($match->tournament)?> : <?=$match->date ?> <br>
        <?=$match->host ?> - <?=$match->guest ?> - <?= $match->gett; ?>:<?= $match->lett; ?>
    </p>
    <?php elseif(strstr($match->host, $team_name) && $match->gett < $match->lett) : ?>
        <p class="mtch" id="head_<?= $match->id ?>"
           onclick="$('#view_<?= $match->id ?>').show(); $(this).hide();"
           style="color: #FF5722">
            <?=\core\helpers\SoccerHelper::getTourFromMatchTournament($match->tournament)?> : <?=$match->date ?> <br>
            <?=$match->host ?> - <?=$match->guest ?> - <?= $match->gett; ?>:<?= $match->lett; ?>
        </p>
    <?php elseif(strstr($match->guest, mb_strcut($team_name,2)) && $match->gett > $match->lett) : ?>
        <p class="mtch" id="head_<?= $match->id ?>"
           onclick="$('#view_<?= $match->id ?>').show(); $(this).hide();"
           style="color: #FF5722">
            <?=\core\helpers\SoccerHelper::getTourFromMatchTournament($match->tournament)?> : <?=$match->date ?> <br>
            <?=$match->host ?> - <?=$match->guest ?> - <?= $match->gett; ?>:<?= $match->lett; ?>
        </p>
    <?php elseif(strstr($match->guest, mb_strcut($team_name,2)) && $match->gett == $match->lett) : ?>
        <p class="mtch" id="head_<?= $match->id ?>"
           onclick="$('#view_<?= $match->id ?>').show(); $(this).hide();"
           style="color: #00BCD4">
            <?=\core\helpers\SoccerHelper::getTourFromMatchTournament($match->tournament)?> : <?=$match->date ?> <br>
            <?=$match->host ?> - <?=$match->guest ?> - <?= $match->gett; ?>:<?= $match->lett; ?>
        </p>
    <?php elseif(strstr($match->host, $team_name) && $match->gett == $match->lett) : ?>
        <p class="mtch" id="head_<?= $match->id ?>"
             onclick="$('#view_<?= $match->id ?>').show(); $(this).hide();"
             style="color: #00BCD4">
              <?=\core\helpers\SoccerHelper::getTourFromMatchTournament($match->tournament)?> : <?=$match->date ?> <br>
              <?=$match->host ?> - <?=$match->guest ?> - <?= $match->gett; ?>:<?= $match->lett; ?>
        </p>
    <?php else : ?>
      <p class="mtch" id="head_<?= $match->id ?>"
         onclick="$('#view_<?= $match->id ?>').show(); $(this).hide();"
         style="color: #eaff55">
          <?=($team_name) ? \core\helpers\SoccerHelper::getTourFromMatchTournament($match->tournament) : $match->tournament?> : <?=$match->date ?> <br>
          <?=$match->host ?> - <?=$match->guest ?> - <?= $match->gett; ?>:<?= $match->lett; ?>
      </p>
    <?php endif; ?>

<div class="view" id="view_<?= $match->id ?>">


    <p id="match_date">
        <?= $match->date ?>
    </p>


    <p id="match_tour"  title="Все матчи <?=$match->tournament?>" onclick="getTour('<?=$match->tournament?>', '<?=$match->tournament_id ?>')">
        <?php echo $match->tournament; ?>
    </p>


    <table id="mems_match" cellpadding="0" >
        <tr>
            <td class="left"
                title="Состав: <?=$match->getSost_h()?>"
                style="cursor: pointer"
                onclick="getTournamentMatchesOfTeam('<?=$match->host?>', '<?=$match->tournament_id?>');">
                <?= $match::cutAfterBracket($match->host); ?></td>
            <td class="center"><?php echo $match->gett; ?>:<?php echo $match->lett; ?> </td>
            <td class="right"
                title="Состав: <?=$match->getSost_g()?>"
                style="cursor: pointer"
                onclick="getTournamentMatchesOfTeam('<?=$match->guest?>', '<?=$match->tournament_id?>');">
                <?= $match::cutAfterBracket($match->guest); ?></td>

        </tr>
        <tr>
            <td class="left small-font" id="left_<?=$match->id?>" onclick="clearSost('left_<?=$match->id?>')"></td>
            <td class="center "></td>
            <td class="right small-font" id="right_<?=$match->id?>" onclick="clearSost('right_<?=$match->id?>')"></td>
        </tr>

    </table>
    <?php if($match->prim) : ?>
        <span class="prim"><?=$match->prim ?></span>
    <?php endif; ?>
    <?php if($match->goul_h || $match->goul_g) :  ?>
        <table id="mems_goal" cellpadding="0" >
            <tr>
                <td class="left"><?php echo $match->goalH_str(); ?><?php echo $match->redCardH_str(); ?><?php echo $match->penMissH_str(); ?></td>
                <td class="center"><span class="fa fa-futbol-o fa-2x"></span></td>
                <td class="right"><?php echo $match->goalG_str(); ?><?php echo $match->redCardG_str(); ?><?php echo $match->penMissG_str(); ?></td>

            </tr>
        </table>
    <?php endif; ?>
    <?php if($match->substit_h || $match->substit_g) : ?>
        <table id="substit" cellpadding="0" >
            <tr>
                <td class="left"><?php $match->substitH_str(); ?></td>
                <td class="center"><span class="glyphicon glyphicon-resize-horizontal"></span></td>
                <td class="right"><?php $match->substitG_str(); ?></td>

            </tr>
        </table>
    <?php endif; ?>
    <?php if($match->getCoachH() != '' || $match->getCoachG() != '') : ?>

        <table id="coach" cellpadding="0" >
            <tr>
                <td class="left"><?php echo $match->getCoachH(); ?></td>
                <td class="center">трен</td>
                <td class="right"><?php echo $match->getCoachG(); ?></td>

            </tr>
        </table>

    <?php endif; ?>
    <?php if($match->getKeeperH() != '' || $match->getKeeperG() != '') : ?>

        <table id="keeper" cellpadding="0" >
            <tr>
                <td class="left"><?php echo $match->getKeeperH(); ?></td>
                <td class="center">врат</td>
                <td class="right"><?php echo $match->getKeeperG(); ?></td>

            </tr>
        </table>

    <?php endif; ?>

    <?php if($match->saves_h != 0 || $match->saves_g != 0) : ?>

        <table id="keeper" cellpadding="0" >
            <tr>
                <td class="left"><?php echo $match->saves_h; ?></td>
                <td class="center">сейв</td>
                <td class="right"><?php echo $match->saves_g; ?> </td>

            </tr>
        </table>

    <?php endif; ?>

    <?php if($match->ud_h != 0 && $match->ud_g != 0) : ?>

        <table id="ud" cellpadding="0" >
            <tr>
                <td class="left"><?php echo $match->ud_h; ?></td>
                <td class="center">удар</td>
                <td class="right"><?php echo $match->ud_g; ?></td>

            </tr>
        </table>

    <?php endif; ?>

    <?php if($match->ud_v_stv_h != 0 || $match->ud_v_stv_g != 0) : ?>

        <table id="ud" cellpadding="0" >
            <tr>
                <td class="left"><?php echo $match->ud_v_stv_h; ?></td>
                <td class="center">створ</td>
                <td class="right"><?php echo $match->ud_v_stv_g; ?></td>

            </tr>
        </table>

    <?php endif; ?>

    <?php if($match->corner_h != 0 && $match->corner_g != 0) : ?>

        <table id="ud" cellpadding="0" >
            <tr>
                <td class="left"><?php echo $match->corner_h; ?></td>
                <td class="center">угл</td>
                <td class="right"><?php echo $match->corner_g; ?></td>

            </tr>
        </table>

    <?php endif; ?>

    <?php if($match->outs_h != 0 && $match->outs_g != 0) : ?>

        <table id="ud" cellpadding="0" >
            <tr>
                <td class="left"><?php echo $match->outs_h; ?></td>
                <td class="center">аут</td>
                <td class="right"><?php echo $match->outs_g; ?></td>

            </tr>
        </table>

    <?php endif; ?>

    <?php if($match->ballpos_h != 0 && $match->ballpos_g != 0) : ?>

        <table id="vlad" cellpadding="0" >
            <tr>
                <td class="left"><?php echo $match->ballpos_h; ?></td>
                <td class="center">% влад</td>
                <td class="right"><?php echo $match->ballpos_g; ?></td>

            </tr>
        </table>

    <?php endif; ?>

    <?php if($match->falls_h != 0 && $match->falls_g != 0) : ?>

        <table id="falls" cellpadding="0" >
            <tr>
                <td class="left"><?php echo $match->yellCardCount_h(); ?><?php echo $match->falls_h; ?></td>
                <td class="center">фол</td>
                <td class="right"><?php echo $match->falls_g; ?><?php echo $match->yellCardCount_g(); ?></td>

            </tr>
        </table>

    <?php endif; ?>

    <?php if($match->bet_h != 0 && $match->bet_n != 0 && $match->bet_g != 0) : ?>

        <table id="stavki" cellpadding="0" >
            <tr>
                <td class="left"></td>
                <td class="center"> ставки </td>
                <td class="right"></td>

            </tr>
        </table>
        <table id="stavki" cellpadding="0" >
            <tr>
                <td class="left"><?php echo $match->bet_h; ?></td>
                <td class="center"><?php echo $match->bet_n; ?> </td>
                <td class="right"><?php echo $match->bet_g; ?></td>

            </tr>
        </table>

    <?php endif; ?>

    <p class="info">
        <?php $match->getInfo(); ?>
    </p>


</div>
<script>
    function getTour(tour, tournament_id) {
        $.ajax({
            type: "GET",
            url: "tournament/get-matches-of-tour",
            data:  'tour=' + tour + '&tournament_id=' + tournament_id,
            success: function(res){
                $("#matches").html(res);
                $("#get-matches").hide();
                $("#tournament").hide();
                $("#get-tournament").show();
            }
        });
    }


    function getTournamentMatchesOfTeam(team, tournament_id, team_block_id, matches_filter=0) {
        $.ajax({
            type: "GET",
            url: "tournament/get-matches-of-team",
            data:  'name=' + team + '&tournament_id=' + tournament_id + '&filter=' + matches_filter,
            success: function(res){
                $("#matches").html(res);
                $("#get-matches").hide();
                $("#tournament").hide();
                $("#get-tournament").show();
                //$(window).scrollTop('#'+team_block_id);
                //$('body').scrollTo('#'+team_block_id); // Scroll screen to target element
                $('html, body').animate({
                    scrollTop: $(document).height()
                }, 2000);

            }
        });
    }
</script>

soccer/views/tournament/teams.php
<?php
/**
 * @var $tournament_id integer
 */
?>
<div id="search-form">
    <p>
        <input type="text" class="form-control" id="team" placeholder="Команда">
    </p>

</div>

<button type="submit" class="btn-success" onclick="getMatches()" id="get-matches-of-team">Матчи</button>

<div id="matches"></div>


<script>
    $(document).ready(function() {

        $('#team').focus(
            function () {
                $(this).select();
            });

        $('#team').autoComplete({
            minChars: 3,
            source: function (term, suggest) {
                console.log(term);
                term = term.toLowerCase();

                $.getJSON("tournament/teams/<?= $tournament_id ?>", function (data) {
                    console.log(data);
                    choices = data;
                    var suggestions = [];
                    for (i = 0; i < choices.length; i++)
                        if (~choices[i].toLowerCase().indexOf(term)) suggestions.push(choices[i]);
                    suggest(suggestions);

                }, "json");

            }
        });

    });

    function getMatches() {

        var team = $("#team").val();
        $.ajax({
            type: "GET",
            url: "tournament/get-matches-of-team",
            data:  'name=' + team + '&tournament_id=' + <?= $tournament_id ?>,
            success: function(res){
                $("#matches").html(res);
                $("#get-matches").hide();
                $("#tournament").hide();
                $("#get-tournament").show();
            }
        });
    }
</script>